export const site = {
  name: "Tomás Maritano",
  handle: "tomás",
  headline: "I ship products.",
  line: "I extract messy inputs into structured data, then generate the document someone will send.",
  city: "Buenos Aires",
  x: "https://x.com/tomymaritano",
  xHandle: "tomymaritano",
  email: "tomymaritano@gmail.com",
  github: "https://github.com/tomymaritano",
  linkedin: "https://www.linkedin.com/in/tomymaritano",
  url: "https://tomymaritano.com",
  photo: "/perfil.png",
  about: [
    "I take a messy input and produce a document a person will send — not a dump of the model. I'm a senior full-stack engineer at Psynth (sole lead on engineering). I joined as a design engineer.",
    "I was twelve, making brochure sites on a CMS. Client pages, not products. Buenos Aires. I studied at Universidad Tecnológica Nacional.",
    "Su Web Express hired me in 2017. Then Wolt in Copenhagen, Grandvalira in Andorra, Valere Realms, Unicoin in 2024. Frontend first, then the stack under it. I did not abandon the surface. I started owning what it sits on. I write when the decision is interesting.",
  ],
  contributions: [
    {
      href: "https://dripnex.app",
      title: "Dripnex",
      lead: "Built ",
      tail: ", a hackable AI note taker. SQLite now — local today so the same notes can sync when other surfaces ship.",
    },
    {
      href: "https://psynth.ai",
      title: "Psynth",
      lead: "Senior full-stack engineer (sole lead) at ",
      tail: ". Test results and intake become a draft the psychologist reviews and signs. I joined as a design engineer.",
    },
    {
      href: "https://dolargaucho.com",
      title: "DolarGaucho",
      lead: "Built ",
      tail: ". Quotes and a model that reads the Argentine week, so someone can trust the strip and move on.",
    },
    {
      href: "https://readied.app",
      title: "Readied",
      lead: "Built ",
      tail: ", an offline-first Markdown editor. Notes stay as plain files on your machine. No proprietary format. No vendor holding the words.",
    },
    {
      href: "https://tomymaritano.github.io/criterionx/",
      title: "Criterion",
      lead: "Built ",
      tail: ", a deterministic decision engine. Same input, same output, and a reason you can show when someone asks why.",
    },
    {
      href: "https://react-cairn.vercel.app",
      title: "Cairn",
      lead: "Built ",
      tail: ", a state-machine workflow engine. You own the UI. Cairn owns the path, the branches, and the event stream.",
    },
  ],
  stack: [
    { label: "Cloud", items: ["AWS", "GCP", "Vercel", "Kubernetes", "Docker", "Terraform", "ArgoCD", "CodeArtifact"] },
    { label: "Frontend", items: ["TypeScript", "JavaScript", "React", "Next.js", "Svelte", "HTMX", "CSS", "Tailwind", "Three.js"] },
    { label: "Native", items: ["Swift", "React Native", "Electron"] },
    { label: "Backend", items: ["Python", "Node.js", "FastAPI", "Hono", "Express", "tRPC", "Go", "Rust"] },
    { label: "Data", items: ["PostgreSQL", "SQLite", "MongoDB", "Redis", "Prisma"] },
    { label: "Content", items: ["Sanity", "Cloudinary", "MDX"] },
    { label: "AI", items: ["Vertex AI", "Bedrock", "Anthropic", "LLM orchestration", "PyTorch", "Reinforcement learning"] },
    { label: "Keyboards", items: ["QMK", "ZMK", "Lua", "C#"] },
  ],
} as const;

export const work = [
  {
    kind: "work" as const,
    slug: "devwifi",
    title: "DevWifiBar",
    line: "Menu bar radar for AI traffic. Nothing inside TLS.",
    started: 2026,
    date: "2026-08-20",
    year: "2026—",
    href: null as string | null,
    repo: "https://github.com/tomymaritano/devwibar",
    cover: "/work/devwifi/cover.svg",
    loop: undefined as string | undefined,
    stills: ["/work/devwifi/radar.svg"],
  },
  {
    kind: "work" as const,
    slug: "dripnex",
    title: "Dripnex",
    line: "Hackable AI note taker. SQLite now, sync next.",
    started: 2026,
    date: "2026-08-18",
    year: "2026—",
    href: "https://dripnex.app",
    repo: "https://github.com/dripnex/readide",
    cover: "/work/dripnex/cover.svg",
    loop: undefined as string | undefined,
    stills: ["/work/dripnex/01.svg", "/work/dripnex/02.svg", "/work/dripnex/03.svg"],
  },
  {
    kind: "work" as const,
    slug: "psynth",
    title: "Psynth",
    line: "Clinical reporting. Senior full-stack / sole lead.",
    started: 2026,
    date: "2026-08-01",
    year: "2026—",
    href: "https://psynth.ai",
    repo: null as string | null,
    cover: "/work/psynth/cover.svg",
    loop: undefined as string | undefined,
    stills: ["/work/psynth/01.svg", "/work/psynth/02.svg", "/work/psynth/03.svg"],
  },
  {
    kind: "work" as const,
    slug: "quantis-intel",
    title: "Quantis-intel",
    line: "The financial report a desk will send.",
    started: 2026,
    date: "2026-07-15",
    year: "2026",
    href: null as string | null,
    repo: null as string | null,
    cover: "/work/quantis-intel/cover.svg",
    loop: undefined as string | undefined,
    stills: ["/work/quantis-intel/cover.svg"],
  },
  {
    kind: "work" as const,
    slug: "cairn",
    title: "Cairn",
    line: "Onboarding as a state machine, not a tooltip list.",
    started: 2026,
    date: "2026-06-14",
    year: "2026",
    href: "https://react-cairn.vercel.app",
    repo: "https://github.com/tomymaritano/cairn",
    cover: undefined as string | undefined,
    loop: undefined as string | undefined,
    stills: [] as string[],
  },
  {
    kind: "work" as const,
    slug: "minipix",
    title: "Minipix",
    line: "Same bytes in JS, Python, and Rust.",
    started: 2026,
    date: "2026-06-13",
    year: "2026",
    href: null as string | null,
    repo: "https://github.com/tomymaritano/minipix",
    cover: undefined as string | undefined,
    loop: undefined as string | undefined,
    stills: [] as string[],
  },
  {
    kind: "work" as const,
    slug: "readied",
    title: "Readied",
    line: "Notes as plain files on your machine.",
    started: 2026,
    date: "2026-03-01",
    year: "2026",
    href: "https://readied.app",
    repo: "https://github.com/tomymaritano/readide",
    cover: undefined as string | undefined,
    loop: undefined as string | undefined,
    stills: [] as string[],
  },
  {
    kind: "work" as const,
    slug: "dolargaucho",
    title: "DolarGaucho",
    line: "Quotes and a model that reads the Argentine week.",
    started: 2025,
    date: "2025-08-01",
    year: "2025—",
    href: "https://dolargaucho.com",
    repo: null as string | null,
    cover: "/work/dolargaucho/cover.svg",
    loop: undefined as string | undefined,
    stills: ["/work/dolargaucho/01.svg", "/work/dolargaucho/02.svg", "/work/dolargaucho/03.svg"],
  },
  {
    kind: "work" as const,
    slug: "criterionx",
    title: "Criterion",
    line: "Same input, same output, and a reason.",
    started: 2025,
    date: "2025-12-29",
    year: "2025",
    href: "https://tomymaritano.github.io/criterionx/",
    repo: "https://github.com/tomymaritano/criterionx",
    cover: undefined as string | undefined,
    loop: undefined as string | undefined,
    stills: [] as string[],
  },
  {
    kind: "work" as const,
    slug: "unicoin",
    title: "Unicoin",
    line: "Crypto with a real-asset story.",
    started: 2024,
    date: "2024-06-01",
    year: "2024",
    href: "https://unicoin.com/",
    repo: null as string | null,
    cover: "/work/unicoin/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/unicoin/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "unicorn-hunters",
    title: "Unicorn Hunters",
    line: "A TV show that can take the check.",
    started: 2024,
    date: "2024-05-01",
    year: "2024",
    href: "https://unicornhunters.com/",
    repo: null as string | null,
    cover: "/work/unicorn-hunters/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/unicorn-hunters/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "silvina-moschini",
    title: "Silvina Moschini",
    line: "Lead with the talk, not the bio.",
    started: 2024,
    date: "2024-04-01",
    year: "2024",
    href: "https://silvinamoschini.com/",
    repo: null as string | null,
    cover: "/work/silvina-moschini/cover.gif",
    loop: undefined as string | undefined,
    stills: ["/work/silvina-moschini/cover.gif"],
  },
  {
    kind: "work" as const,
    slug: "billspace",
    title: "BillSpace",
    line: "Cancel one Dutch bill without a local friend.",
    started: 2025,
    date: "2025-05-01",
    year: "2025",
    href: "https://www.billspace.eu/",
    repo: null as string | null,
    cover: "/work/billspace/cover.jpg",
    loop: undefined as string | undefined,
    stills: ["/work/billspace/cover.jpg"],
  },
  {
    kind: "work" as const,
    slug: "heirloom",
    title: "Heirloom",
    line: "Life notes without the feed.",
    started: 2025,
    date: "2025-04-01",
    year: "2025",
    href: "https://getheirloom.app/",
    repo: null as string | null,
    cover: "/work/heirloom/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/heirloom/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "jetsetz",
    title: "Jetsetz",
    line: "Show the deal, not fifteen filters.",
    started: 2025,
    date: "2025-03-01",
    year: "2025",
    href: "https://jetsetz.com/",
    repo: null as string | null,
    cover: "/work/jetsetz/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/jetsetz/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "lego-store",
    title: "LEGO Store",
    line: "An e-commerce template you can resell.",
    started: 2025,
    date: "2025-12-09",
    year: "2025",
    href: "https://lego-ecommerce-five.vercel.app/",
    repo: "https://github.com/tomymaritano/lego-store",
    cover: "/work/lego-store/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/lego-store/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "turbotime",
    title: "TurboTime",
    line: "Name the jobs Excel was actually doing.",
    started: 2025,
    date: "2025-02-01",
    year: "2025",
    href: "https://www.figma.com/make/RmxLXzGCZMOamKV3ps8yeL/TurboTime.ai-design-prototype",
    repo: null as string | null,
    cover: "/work/turbotime/cover.gif",
    loop: undefined as string | undefined,
    stills: ["/work/turbotime/cover.gif"],
  },
  {
    kind: "work" as const,
    slug: "viny",
    title: "Viny",
    line: "The file is the source of truth.",
    started: 2025,
    date: "2025-01-15",
    year: "2025",
    href: null as string | null,
    repo: "https://github.com/tomymaritano/viny",
    cover: "/work/viny/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/viny/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "menkiki",
    title: "Menkiki",
    line: "Scan food, find a place nearby.",
    started: 2025,
    date: "2025-01-01",
    year: "2025",
    href: null as string | null,
    repo: "https://github.com/tomymaritano/menkiki",
    cover: "/work/menkiki/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/menkiki/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "freedom-people",
    title: "The Freedom People",
    line: "Checkout that feels like Lightning, not a bank.",
    started: 2023,
    date: "2023-08-01",
    year: "2023",
    href: "https://thefreedompeople.org/",
    repo: null as string | null,
    cover: "/work/freedom-people/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/freedom-people/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "blacro",
    title: "Blacro Studio",
    line: "Creative agency site that is the proof.",
    started: 2023,
    date: "2023-06-01",
    year: "2023",
    href: "https://blacro.com/",
    repo: null as string | null,
    cover: "/work/blacro/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/blacro/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "isolla",
    title: "Isolla",
    line: "Furniture, shown at the scale of the piece.",
    started: 2023,
    date: "2023-04-01",
    year: "2023",
    href: "https://isolla.co/",
    repo: null as string | null,
    cover: "/work/isolla/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/isolla/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "g1m",
    title: "G1M",
    line: "Local checkout, not a US template.",
    started: 2023,
    date: "2023-03-01",
    year: "2023",
    href: "https://www.g1m.com.ar/",
    repo: null as string | null,
    cover: "/work/g1m/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/g1m/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "privatelimo",
    title: "Private Limo",
    line: "WhatsApp is the checkout.",
    started: 2023,
    date: "2023-02-01",
    year: "2023",
    href: "https://privatelimo.com.ar/es",
    repo: null as string | null,
    cover: "/work/privatelimo/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/privatelimo/cover.png"],
  },
  {
    kind: "work" as const,
    slug: "grandvalira-sede",
    title: "Grandvalira Sede",
    line: "Roles in the token, checked on every write.",
    started: 2022,
    date: "2022-06-01",
    year: "2022",
    href: null as string | null,
    repo: null as string | null,
    cover: "/work/grandvalira-sede/cover.png",
    loop: undefined as string | undefined,
    stills: ["/work/grandvalira-sede/cover.png"],
  },
] as const;

export const writing = [
  {
    kind: "writing" as const,
    slug: "lily58-is-not-a-bigger-corne",
    title: "A Lily58 is not a bigger Corne",
    line: "58 keys. Linear whites. QMK is the file.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "a-scaffold-is-not-a-decision",
    title: "A scaffold is not a decision",
    line: "criterion new writes TypeScript. validate is a string scan. Do not import core.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "a-run-is-not-a-click",
    title: "A run is not a click",
    line: "run(ctx, signal). Auto-advance on settle. Manual next is ignored while in flight.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "a-span-is-not-a-reason",
    title: "A span is not a reason",
    line: "createTracedEngine wraps run. recordInput defaults off. explain is still the audit trail.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "an-index-is-not-a-path",
    title: "An index is not a path",
    line: "next(ctx). hasTeam ? invite : null. Returning null ends the flow.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "a-dead-rule-is-not-a-ranking",
    title: "A dead rule is not a ranking",
    line: "detectDeadRules. After when: () => true, later ids never fire.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-bar-is-not-the-cli",
    title: "The bar is not the CLI",
    line: "Radar in the bar. pass, qr, speed stay in the toolkit.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-widget-is-not-a-radar",
    title: "The widget is not a radar",
    line: "WidgetKit reads a snapshot. It will not run lsof.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "a-spec-is-not-a-decision",
    title: "A spec is not a decision",
    line: "Operators compile to when. when: always is the default. explain is a description.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-editor-is-not-the-engine",
    title: "The editor is not the engine",
    line: "Highlight, snippet, squiggle the object. Do not import core.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "sync-core-is-not-a-sync-engine",
    title: "sync-core is not a sync engine",
    line: "Contracts and validateNotebookTree. Live sync is SyncService.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-abi-is-not-the-domain",
    title: "The ABI is not the domain",
    line: "better-sqlite3 is one package. Core tests stay plain Node.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-write-port-is-not-the-index",
    title: "The write port is not the index",
    line: "get, save, delete. List and graph live on storage-core.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "gpl-is-not-a-codec",
    title: "GPL is not a codec",
    line: "cargo-deny in CI. avif-parse is the one MPL file.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-popover-is-not-the-firehose",
    title: "The popover is not the firehose",
    line: "flow:start through context:update. Pipe onAny. Do not invent a tracker.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "an-extension-is-not-a-fork",
    title: "An extension is not a fork",
    line: "registerEditorExtension. The host reconfigures. Do not patch core.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "wasm-is-not-native",
    title: "Wasm is not native",
    line: "mozjpeg stays on the native path. PNG and AVIF still match.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "packages-are-not-a-platform",
    title: "Packages are not a platform",
    line: "Core is a knife. Server, React, and MCP call it.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-core-has-no-clock",
    title: "The core has no clock",
    line: "No fetch, no database, no Date.now. Pass the object.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "a-profile-is-not-a-fork",
    title: "A profile is not a fork",
    line: "Same function. US and EU change the threshold, not the rule.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "first-match-wins",
    title: "First match wins",
    line: "Rules run in order. The default is `when: () => true`.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "a-reload-is-not-a-restart",
    title: "A reload is not a restart",
    line: "load, save, remove. Finished must not replay.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-preview-is-not-the-file",
    title: "The preview is not the file",
    line: "The editor keeps the URL. YouTube is a render.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "a-checkbox-is-not-a-row",
    title: "A checkbox is not a row",
    line: "`- [ ]` is Markdown. Aggregation is derived.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "default-is-not-a-palette",
    title: "Default is not a palette",
    line: "tokens.css is core. Named palettes are tarballs.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "a-backlink-is-not-a-copy",
    title: "A backlink is not a copy",
    line: "[[note title]] is Markdown. The graph is derived.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "search-is-local",
    title: "Search is local",
    line: "Operators on this machine. An account is not a requirement.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "tags-are-not-the-body",
    title: "Tags are not the body",
    line: "Notebooks, status, and pin live beside the Markdown. They do not rewrite it.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "ssid-is-not-free",
    title: "SSID is not free",
    line: "Location names the network. The radar does not need it.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "a-recalc-is-not-a-new-ingest",
    title: "A recalc is not a new ingest",
    line: "Five named drivers. Status is the last pull, not a fake bar.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "a-hack-is-not-a-pack",
    title: "A hack is not a pack",
    line: "Settings → Hack is yours. A tarball is how you share.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "signing-in-is-not-uploading",
    title: "Signing in is not uploading",
    line: "AuthGate is first launch. Don't Sync is valid. Ciphertext is optional.",
    started: 2026,
    date: "2026-08-28",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-renderer-never-sees-sql",
    title: "The renderer never sees SQL",
    line: "Core is operations. IPC is the contract. Storage is an adapter.",
    started: 2026,
    date: "2026-08-27",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-file-is-the-export",
    title: "The file is the export",
    line: "Raw markdown is canonical. The AST is ephemeral.",
    started: 2026,
    date: "2026-08-26",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-note-came-first",
    title: "The note came first. The names came in one night",
    line: "I named the jobs in the order the surfaces split.",
    started: 2026,
    date: "2026-08-22",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-radio-is-fine",
    title: "The radio is fine",
    line: "Name the helper filling the pipe. Leave TLS sealed.",
    started: 2026,
    date: "2026-08-21",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "sqlite-is-the-store",
    title: "Plain files are easy to romanticize",
    line: "SQLite is the source of truth. Sync is a later surface.",
    started: 2026,
    date: "2026-08-18",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-plugin-is-a-git-repo",
    title: "The plugin is a git repo",
    line: "One repo. A tag. A tarball. No store that holds the words.",
    started: 2026,
    date: "2026-08-19",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-file-has-to-stay-readable",
    title: "The file has to stay readable",
    line: "Local-first is the product. Markdown is not a cache.",
    started: 2026,
    date: "2026-03-02",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "engine-is-not-the-renderer",
    title: "The engine is not the renderer",
    line: "A tooltip dies when the DOM changes. A state machine survives navigation.",
    started: 2026,
    date: "2026-06-15",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "byte-identical",
    title: "Byte-identical or it did not ship",
    line: "One Rust core. Three languages. SHA-256 goldens in CI.",
    started: 2026,
    date: "2026-06-13",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "grok-bot-and-cursor",
    title: "Grok 4.6 in Cursor is not Grok Bot",
    line: "One loop lives in the repo. The other has a computer.",
    started: 2026,
    date: "2026-08-20",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "corne-keyboard",
    title: "A Corne is a 42-key contract",
    line: "Layers are the product. The PCB is just the case.",
    started: 2026,
    date: "2026-08-20",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "section-generation-pipeline",
    title: "How a report section is generated",
    line: "If gen and regen are two products, they drift.",
    started: 2026,
    date: "2026-08-16",
    year: "2026",
  },
  {
    kind: "writing" as const,
    slug: "the-quote-is-not-the-product",
    title: "The quote is not the product",
    line: "The week is a desk. The number is a UI problem.",
    started: 2025,
    date: "2025-08-15",
    year: "2025",
  },
  {
    kind: "writing" as const,
    slug: "claude-code-pm",
    title: "Claude Code is not a ticket translator",
    line: "Prototype the spec before you file it.",
    started: 2025,
    date: "2025-10-03",
    year: "2025",
  },
  {
    kind: "writing" as const,
    slug: "if-you-cannot-show-why",
    title: "If you cannot show why, it is not a decision",
    line: "Same input, same output, and a reason you can send.",
    started: 2025,
    date: "2025-12-30",
    year: "2025",
  },
  {
    kind: "writing" as const,
    slug: "threejs-sanity-integration",
    title: "The canvas does not wait on Sanity",
    line: "Fetch first. Then mount WebGL.",
    started: 2025,
    date: "2025-07-04",
    year: "2025",
  },
  {
    kind: "writing" as const,
    slug: "cloudinary-migration",
    title: "Binaries do not belong in git",
    line: "450MB became 1.2MB. The hour was the cheap part.",
    started: 2025,
    date: "2025-07-03",
    year: "2025",
  },
  {
    kind: "writing" as const,
    slug: "ai-business-validation",
    title: "The model did not replace the calls",
    line: "A week of interviews, not a month of nights.",
    started: 2025,
    date: "2025-06-15",
    year: "2025",
  },
] as const;

export type WorkItem = (typeof work)[number];
export type WorkSlug = WorkItem["slug"];
export type WritingItem = (typeof writing)[number];
export type WritingSlug = WritingItem["slug"];
export type IndexItem = WorkItem | WritingItem;
export type WorkLane = "product" | "role" | "client";

export const workLanes = {
  devwifi: "product",
  dripnex: "product",
  psynth: "product",
  "quantis-intel": "product",
  cairn: "product",
  minipix: "product",
  readied: "product",
  dolargaucho: "product",
  criterionx: "product",
  unicoin: "role",
  "unicorn-hunters": "client",
  "silvina-moschini": "client",
  billspace: "client",
  heirloom: "product",
  jetsetz: "client",
  "lego-store": "product",
  turbotime: "product",
  viny: "product",
  menkiki: "product",
  "freedom-people": "client",
  blacro: "product",
  isolla: "client",
  g1m: "client",
  privatelimo: "client",
  "grandvalira-sede": "role",
} as const satisfies Record<WorkSlug, WorkLane>;

export const workLaneLabel: Record<WorkLane, string> = {
  product: "Product",
  role: "Role",
  client: "Client",
};

export const workNotes = {
  psynth: "section-generation-pipeline",
  cairn: "engine-is-not-the-renderer",
  minipix: "byte-identical",
  criterionx: "if-you-cannot-show-why",
  dripnex: "sqlite-is-the-store",
  devwifi: "the-radio-is-fine",
  dolargaucho: "the-quote-is-not-the-product",
  readied: "the-file-has-to-stay-readable",
} as const satisfies Partial<Record<WorkSlug, WritingSlug>>;

export const noteCases = {
  "the-file-is-the-export": "dripnex",
  "the-renderer-never-sees-sql": "dripnex",
  "signing-in-is-not-uploading": "dripnex",
  "a-hack-is-not-a-pack": "dripnex",
  "tags-are-not-the-body": "dripnex",
  "search-is-local": "dripnex",
  "a-backlink-is-not-a-copy": "dripnex",
  "default-is-not-a-palette": "dripnex",
  "a-checkbox-is-not-a-row": "dripnex",
  "the-preview-is-not-the-file": "dripnex",
  "the-write-port-is-not-the-index": "dripnex",
  "the-abi-is-not-the-domain": "dripnex",
  "sync-core-is-not-a-sync-engine": "dripnex",
  "an-extension-is-not-a-fork": "dripnex",
  "the-plugin-is-a-git-repo": "dripnex",
  "the-note-came-first": "dripnex",
  "an-index-is-not-a-path": "cairn",
  "a-reload-is-not-a-restart": "cairn",
  "the-popover-is-not-the-firehose": "cairn",
  "the-core-has-no-clock": "cairn",
  "a-run-is-not-a-click": "cairn",
  "wasm-is-not-native": "minipix",
  "gpl-is-not-a-codec": "minipix",
  "packages-are-not-a-platform": "criterionx",
  "first-match-wins": "criterionx",
  "a-profile-is-not-a-fork": "criterionx",
  "a-scaffold-is-not-a-decision": "criterionx",
  "a-spec-is-not-a-decision": "criterionx",
  "a-span-is-not-a-reason": "criterionx",
  "a-dead-rule-is-not-a-ranking": "criterionx",
  "the-editor-is-not-the-engine": "criterionx",
  "ssid-is-not-free": "devwifi",
  "the-bar-is-not-the-cli": "devwifi",
  "the-widget-is-not-a-radar": "devwifi",
  "a-recalc-is-not-a-new-ingest": "dolargaucho",
} as const satisfies Partial<Record<WritingSlug, WorkSlug>>;

export function workLane(slug: WorkSlug): WorkLane {
  return workLanes[slug];
}

export function workBySlug(slug: string): WorkItem | null {
  return work.find((item) => item.slug === slug) ?? null;
}

export function workForNote(slug: string): WorkItem | null {
  const found = (Object.entries(workNotes) as [WorkSlug, WritingSlug][]).find(([, note]) => note === slug);
  if (found) return workBySlug(found[0]);
  const extra = slug in noteCases ? noteCases[slug as keyof typeof noteCases] : null;
  return extra ? workBySlug(extra) : null;
}

export function writingBySlug(slug: string): WritingItem | null {
  return writing.find((item) => item.slug === slug) ?? null;
}

export function itemPath(item: IndexItem) {
  return item.kind === "writing" ? `/writing/${item.slug}` : `/work/${item.slug}`;
}

function datedIndex<T extends IndexItem>(items: readonly T[]) {
  const sorted = [...items].sort((a, b) => b.date.localeCompare(a.date));
  let lastYear: number | null = null;
  return sorted.map((item) => {
    const showYear = item.started !== lastYear;
    lastYear = item.started;
    return { ...item, showYear, path: itemPath(item) };
  });
}

export const homeSlugs = ["psynth", "dripnex", "dolargaucho", "quantis-intel"] as const;

export type HomeSlug = (typeof homeSlugs)[number];

export const homeMeta = {
  psynth: { tag: "Clinical reporting", role: "Senior Full Stack Engineer" },
  dripnex: { tag: "Hackable AI notes" },
  dolargaucho: { tag: "AI finance" },
  "quantis-intel": { tag: "Financial reporting" },
} as const;

export function isHomeSlug(slug: string): slug is HomeSlug {
  return (homeSlugs as readonly string[]).includes(slug);
}

export function homeWork() {
  return homeSlugs.map((slug) => workBySlug(slug)).filter((item): item is WorkItem => item !== null);
}

export function workIndex() {
  return datedIndex(work);
}

export function workSections() {
  const lanes: WorkLane[] = ["product", "role", "client"];
  const titles: Record<WorkLane, string> = {
    product: "Products",
    role: "Roles",
    client: "Clients",
  };
  return lanes
    .map((lane) => ({
      lane,
      title: titles[lane],
      items: datedIndex(work.filter((item) => workLanes[item.slug] === lane && !isHomeSlug(item.slug))),
    }))
    .filter((section) => section.items.length > 0);
}

export function writingIndex() {
  return datedIndex(writing);
}

export function neighbors<T extends { slug: string }>(items: readonly T[], slug: string) {
  const index = items.findIndex((item) => item.slug === slug);
  if (index < 0) return { newer: null, older: null };
  return {
    newer: items[index - 1] ?? null,
    older: items[index + 1] ?? null,
  };
}

export function writingNeighbors(slug: string) {
  return neighbors(writingIndex(), slug);
}

export function workNeighbors(slug: string) {
  return neighbors(workIndex(), slug);
}

export function formatDate(iso: string) {
  return new Date(`${iso}T00:00:00`).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}
